### PR TITLE
Created Czech translation for ...? module

### PR DESCRIPTION
**Pull request by Cirax856**

### CODE REVIEW

**Comment by Luminoscity** [comment]
@Cirax856 Once again please don't forget to add .html to the file extension. Also how are you making these? If you had actually opened that file on your computer you would have caught that it's not an HTML file. So how are you looking at the file to make sure the manual looks the way you want? "?" isn't even an allowed character in the Windows filesystem.

**Comment by Cirax856** [comment]
Ugh I keep forgetting. Sorry.
Well I have a template manual folder that I always copy the source code of the manual to. I named it ...Q and on github I just renamed it to ...?. The template folder I have has all the css, js, img files, but of course the SVG won't load, because I am not going to install it for the manual locally. I hope this makes sense, I will try to include the .html from now on, I just don't know why I keep forgetting.

**Comment by Luminoscity** [comment]
Okay that makes sense. But you should name the file exactly what you name it on your computer. Because `...?` is an invalid filename.

**Comment by Cirax856** [comment]
okay let me rename it

**Comment by Luminoscity** [comment]
By the way, don't be fooled by those filenames that **_seem_** to have question marks in their filename, it's actually a unicode character that looks like a question mark.

**Comment by Cirax856** [comment]
Interesting...

**Pull request merged**
