### PR TITLE
Additional update to translation JSONs

### PR DESCRIPTION
**Pull request by SierraTango1920**
To be pulled at the same time as PR Timwi/KtaneWeb#118 on KtaneWeb.

### CODE REVIEW

**Comment by Luminoscity** [comment]
@SierraTango1920 Please don't update the same the same file twice in two different pull requests. Just make all your changes to that one file in the first pull request.

**Comment by SierraTango1920** [comment]
I will be making all changes on this pull request, to be clear

**Comment by Luminoscity** [comment]
@SierraTango1920 FYI to update anything in en.json (not the other ones though), update the string in KtaneWeb TranslationInfo.cs and then just run KtaneWeb and it will update en.json for you with proper formatting. I think you did it the other way around, updating en.json and then updating KtaneWeb's TranslationInfo.cs because you missed a couple. Don't worry about it this time though.

**Comment by Luminoscity** [comment]
Good to go when Timwi uploads KtaneWeb update

**Comment by Timwi** [comment]
Thank you so much! I took the liberty to re-commit the changes so as to uncouple the spelling fixes (compatibility/GitHub) from the addition of a Czech translation. New commit id: b3856183cd0a5b77e5ea37a241b0fcefa2561e6c

**Pull request closed without merging**
