### PR TITLE
Updated manual and json Tech Support

### PR DESCRIPTION
**Pull request by willem88836**

### CODE REVIEW

**Review by MrPeanut1028 — CHANGES_REQUESTED** [review]
Please see the #maintenance channel in the KTaNE Discord on how to fix this PR, a couple of changes are needed. Thank you.

**Comment by wmeijer221** [comment]
I changed the html file according to your remark; it had been a while since I read the pinned messages. It should all be resolved now.

**Comment by willem88836** [comment]
I changed the html file according to your remark; it had been a while since I read the pinned messages. It should all be resolved now.

**Comment by MrPeanut1028** [comment]
Looks good, thank you for the changes!

**Pull request merged**
