### PR TITLE
Exports and documentation update in svg-utils and Ut

### PR DESCRIPTION
**Pull request by MasQueElite**
Better if this is checked (only) by the author of these files.

### CODE REVIEW

**Comment by Luminoscity** [comment]
This completely breaks all manuals that rely on these libraries.
**Uncaught SyntaxError: Unexpected token 'export'
at Ut.js:282**
**Uncaught SyntaxError: Unexpected token 'export'
at svg-utils.js:44**

**Comment by MasQueElite** [comment]
True. I was so concentrated then on the comments I forgot to test. Thanks. I'll work on it.

**Comment by MasQueElite** [comment]
You have to put `type="module"` in the `<script>` tag if you want to use it from now on. Let me know if that's fine with you.
If it is, I wll begin testing this export feature.

**Comment by MasQueElite** [comment]
Oops. Was updating my fork...
Anyways. To import you'll have to set your tag to `<script type="module">` and then use `import` inside it. That's all.

**Comment by MasQueElite** [comment]
I think it's better if this PR was only about comments. The modules PR is going to be a bit big, since I have to change and adapt some files.

**Pull request merged**
