### PR TITLE
Update tutorial links for base off and matrices

### PR DESCRIPTION
**Pull request by TheKuroEver**
Request: https://discord.com/channels/160061833166716928/612414629179817985/1111275641480949820
Tutorials have been redone by the same person, so they replace the old ones.

### CODE REVIEW

**Comment by TheKuroEver** [comment]
Figured I'd just add that change here since I was going to put them in the same pr anyway if I had confirmation immediately

**Comment by Luminoscity** [comment]
@TheKuroEver  Please don't open a pull request until you are finished making changes on your fork. We get notified of every push you make after the pull request is already open. In the future, please plan to not make any more changes after you have opened the pull request, except for changes requested by a reviewer.

**Comment by TheKuroEver** [comment]
@Luminoscity Ah, sorry about that. Does that also apply to other branches on my fork?

**Comment by Luminoscity** [comment]
I think it's only the branch that you used to open the pull request.

**Pull request merged**
