### PR TITLE
Updated black cipher manual

### PR DESCRIPTION
**Pull request by Deppresso-Exppresso**
Updated digrafid cipher as its unnecessarily complicated as the 3 column part can just be turned 90* CW and making a copy of the 3x3 grid which you also turn 90* 

(Why did i make this?: https://discord.com/channels/777820746558734357/777834860831834113/796513159316766762 )

### CODE REVIEW

**Comment by kavinkul** [comment]
Please don't. If you don't have permission from the original author, you shouldn't edit it. I'm closing this pull request for now.

**Comment by Deppresso-Exppresso** [comment]
> Please don't. If you don't have permission from the original author, you shouldn't edit it. I'm closing this pull request for now.

he literally said i could edit it if i wanted so yes i did get permission like what?

**Comment by kavinkul** [comment]
I wasn't able to check the link. I was informed that you have the permission. Sorry about that. It appears that it is a link to KTANE Academy server which I am not a part of. I will reopen the PR for now. Though do note that your PR has some other issues.

**Comment by Deppresso-Exppresso** [comment]
> > Please don't. If you don't have permission from the original author, you shouldn't edit it. I'm closing this pull request for now.
> 
> he literally said i could edit it if i wanted so yes i did get permission like what?



> I wasn't able to check the link. I was informed that you have the permission. Sorry about that. It appears that it is a link to KTANE Academy server which I am not a part of. I will reopen the PR for now. Though do note that your PR has some other issues.

what problems would that be?

**Comment by kavinkul** [comment]
There were a few commits that you messed up earlier. It would not look nice if I were simply to accept the PR as is. Though, I won't be the one accepting PR at least tonight.

**Comment by Deppresso-Exppresso** [comment]
> There were a few commits that you messed up earlier. It would not look nice if I were simply to accept the PR as is. Though, I won't be the one accepting PR at least tonight.

i'm not the best at github and this is mostly my first time so i made an error to master branch then decides to override it with my code but then i found a spelling error.

**Comment by tepel-chen** [comment]
> There were a few commits that you messed up earlier. It would not look nice if I were simply to accept the PR as is. Though, I won't be the one accepting PR at least tonight.

You can always squash and merge. It's on the options on the right of "Merge pull request" button.

**Pull request merged**
