### PR TITLE
Add KanaPack Modules

### PR DESCRIPTION
**Pull request by Strike-Kaboom**

### CODE REVIEW

**Comment by Luminoscity** [comment]
@Strike-Kaboom FYI, you don't need to provide the PDF, those are generated automatically. Also pictures of tables are not allowed since that kind of graphic can be easily created with actual <table> elements in HTML and pictures of tables don't work well in dark mode, and they don't scale on zoom, and they are not easily translatable, and they take up more bytes than an HTML table. In this case, I will do my best to create the tables in HTML form, but keep these things in mind for your next manual. Also Tags are supposed to be all lowercase for consistency.

**Comment by Luminoscity** [comment]
These modules are very cool.
I am not able to find you on our discord server. But there is a major bug with these two modules. If you ever select one of them, the keyboard capture is bound forever, even if you deselect the module. This will absolutely cause strikes because other modules need keyboard input and your modules will strike if that keyboard input is not the correct solution for the module. So for example if you have more than one of these modules on a bomb and you accidently select one before you are ready to solve it, it is now impossible not to strike on it. So until you fix that, the modules will be marked as Unplayable.

**Comment by Strike-Kaboom** [comment]
Very kind of you to fix those things for me.
The tables and SVGs look fantastic.
As for the Keyboard bug, I asked around for a possible fix but I believe that is a known bug with modkit in regards to OnInteract / Select / Deselect methods.
I have attempted a few things to fix the issue but to no avail.
It only occurs when selecing another module from my modules. If you back out of the module without switching, it deactivates the input. I'm happy to keep it unplayable under that pretext.
There is another known minor bug with the logfile but I'm almost certain it's the logfiles' problem. It produces multiple results when testing the module. In unity, it works fine. Those are the other two bugs I know about right now.
I am also not in the main discord as you mentioned as I simply choose not to be. I am in the TP discord server though; you can find me there if need be.
Thank you for your help.

**Comment by Luminoscity** [comment]
Okay. Perhaps take a look at the source code for "Identification" modules that have keyboard support. Because they do not experience this bug. Like SpongeBob Birthday, or Plant, or Pickup. Whatever they do to fix this should work for your module.

**Comment by Strike-Kaboom** [comment]
Thank you for the advice, I will look into it over the weekend and push a fix when I can.

**Pull request merged**
