### PR TITLE
Kana Manual & JSON updates

### PR DESCRIPTION
**Pull request by Strike-Kaboom**
The keyboard capture bug has been squashed.
This PR also includes a generic manual update.
Thanks in advance!

### CODE REVIEW

**Comment by Luminoscity** [comment]
@Strike-Kaboom More bugs with the module, sometimes there are more than 5 stages. The manual says there are 5 stages. And the logging is messed up. Don't forget to log the module ID (which instance of the module you are printing logging for), otherwise all the logging ends up in the same place even if there are multiple Hiragana (or Katakana) modules on the bomb. See below for how the log is supposed to look for more than one copy of a module (multiple Toolmods, multiple Ars Goetia, multiple Spongebob Birthday) on a bomb.
image
Logfile: https://ktane.timwi.de/More/Logfile%20Analyzer.html#file=0c372fe40f40530887ee1762380ab050f40bedd5;bomb=KD9DN0

See this line of code for an example of how to do that logging: https://github.com/TasThiluna/Ars-Goetia-Identification/blob/master/Assets/arsGoetiaIdentification.cs#L97

**Comment by Strike-Kaboom** [comment]
There are only 5 stages. When you strike, the stage counter does not increment. Which is also why you get the "You answered x times" is in the logfile. If its needed in the manual, we can add something like: "A strike will incur upon an incorrect combination. Stages do not reset & do not increment upon a strike."; if it seems too unclear.

Also, the logfile bug has been fixed. Pushing the update now.
Thank you for merging.

**Comment by Strike-Kaboom** [comment]
I don't understand. The log you provided says: "You answered 5 times" for two of the modules, the log file just had a bug (which has since been fixed) so it shows up twice on one module. I haven't had any issues and neither has anyone else (I know this cause the entire Japanese community would be on my case about it; they have reported other bugs to be already and I thank them for it).
When I decided to mention on the manual that "Stages do not reset", it was telling the player that they do not reset back to 0 (effectively starting over); instead they stay on the same stage they struck on.
Would you like to provide a manual rewording suggestion if it is all this bad? Thank you.

**Comment by Luminoscity** [comment]
I've tested the new version and it does seem that there are 5 stages always now. So I guess the bug went away. I'll change the comment from `A strike will incur upon an incorrect combination. Stages do not reset.` to `A strike will occur upon an incorrect submission and the displayed character(s) will change, but current stage number will not change.`
How's that?

**Comment by Strike-Kaboom** [comment]
Good, I just added a "the" in the mix. Thanks for the suggestion.
A strike will occur upon an incorrect submission and the displayed character(s) will change, but the current stage number will not change.

**Comment by Luminoscity** [comment]
Good catch. Thanks. Nice modules! I like them a lot. I've also added these to the Quiz. https://ktane.timwi.de/More/Quiz.html

**Pull request merged**
