### PR TITLE
Upload and fixes in #request

### PR DESCRIPTION
**Pull request by Limeboy0603**
Upload: 
Espik's encrypted dice, 
Frank's classic wire placement Czech translation. 

Fix: 
Typo in Time Signature

### CODE REVIEW

**Comment by Limeboy0603** [comment]
Btw, ignore the first 3 finished commit. Thx maintainer.

**Comment by red031000** [comment]
please apply all the changes listed in https://docs.google.com/document/d/1F1v94J1EpPJqtK4Km_7GJ1mJgH0keWdISoxvhWVB1tI/edit?usp=sharing

**Comment by red031000** [comment]
please translate the language in the title; czech should be Čeština

**Comment by Limeboy0603** [comment]
hey red here's what I did for all the newly uploaded Czech translation manual

1. changed Czech to Čeština in the file title
2. added pdf for all Czech translation
3. changed short hyphens to longer hyphens

I hope everything is fine. Tell me if there are any problems, I'll try my best

**Comment by red031000** [comment]
looks mostly good, could you minify the svg as well? please use https://jakearchibald.github.io/svgomg/ for that

**Comment by Limeboy0603** [comment]
dude can someone merge this pr to fix the translated manuals

**Pull request merged**
