### PR TITLE
JP manual Update &  some tag fix

### PR DESCRIPTION
**Pull request by hatosableSAN**
I found these line-break tags while the linting

### CODE REVIEW

**Comment by Luminoscity** [comment]
Do you think you could limit the number of HTML files changed to 20 for future pull requests? It's fairly quick to deal with that way and you probably wouldn't have very long to wait for someone to have the time to process the request.

**Comment by hatosableSAN** [comment]
@Luminoscity 
Sure.Is the upper limit of 20, regardless of commit's type?I think adding new files does not equal fixing file small typo.

**Comment by Luminoscity** [comment]
Well ideally you would limit the number of new HTML files to 10 and changed files to 20 for a total of 30. Anything more is quite a bit of work for us to verify.

**Comment by hatosableSAN** [comment]
Right.I will be careful from now on.

**Pull request merged**
