### PR TITLE
New module manuals

### PR DESCRIPTION
**Pull request by TheKuroEver**
* Dice Stack
* Job Application

### CODE REVIEW

**Comment by TheKuroEver** [comment]
The Job Application SVG is quite big. I wasn't sure what to do with it, so I just minified it as much as I could without killing the quality, but maybe it would be more appropriate to make a simpler one.

**Comment by Luminoscity** [comment]
@TheKuroEver For your reference, the SVG looks like that because they did a Bitmap Trace in Inkscape or some other program and didn't bother (or didn't know how) to clean it up afterwards. Admittedly, it is a fairly advanced thing to be able to clean it up by hand in Inkscape or Illustrator.
Before
image

After
image

Could go even further, but that would be like another hour of work.

**Comment by cameronos** [comment]
I did use that function, so sorry for the mess... Thanks for cleaning up my work. It looks really good

**Comment by Luminoscity** [comment]
No worries. In the future, I recommend drawing it yourself in Inkscape instead of using a program to trace a PNG. It will always turn out better and with more efficient SVG code. It's debatable whether there should be any English text in the SVG at all, but my view is that the only text should be text that is always on the module like the label of a button and not any of the text that can change. So like displays would just be a rectangle instead of a rectangle with example text in it. The SVG should be able to help people of all languages identify where the important elements of your module are.

**Pull request merged**
